### ISSUE TITLE
请教前端代码共享问题？

### ISSUE THREAD

**Issue by winixt** [senntyou/blogs#50]
## 场景
一个大的前端团队一起开发多个应用，多个应用间有共享的改变又相对频繁的代码。（个人认为不太适合使用 npm 管理，因为当更改共享代码的时候，需要到每个代码仓库去 update 一遍，然后再发布一遍），目前的想法是所用应用使用同一个代码仓库。

使用同一个代码仓库，即可以解决上述需求，又能解决你之前提到问题：
**统一性：多个项目之间应当使用相同的技术选型、UI 框架、脚手架、开发工具、构建工具、测试库、目录规范、代码规范等，相同功能应指定使用固定某一个库**

但是用统一的框架，我暂时没有好的想法去组织这么一个大的框架？

对此你有什么看法呢？

**Comment by senntyou** [comment]
你提出的第一个问题，多个项目同时依赖一个组件，但这个组件改动又比较频繁，频繁发布组件 npm 包不太具可操作性。

使用 npm 管理依赖，项目做组件化这本身没有问题，但你提到的这种情况需要一些额外的技巧。

项目目录结构

```
- project1
- project2
- component1
```

项目1和项目2都依赖组件1,但组件1有改动比较频繁，一般有两种思路解决这种问题。

*** 第一种是使用 git 来做临时版本处理：***

`component1` 频繁发布诸多个小版本（可以是 `commit, tag, release`, 但以你提到的情况，使用 `commit` 是比较合适的）

```
// package.json | version
1.2.3-alpha.1
1.2.3-alpha.2
1.2.3-alpha.3
1.2.3-alpha.3
1.2.3-beta.1
1.2.3-beta.2
1.2.3-beta.3
1.2.3-beta.4
...
```

在 `project1` 中（以 `github` 仓库地址为例）

```
// package.json | dependencies
"@scope/component1": "^1.2.2" // 正常的发布版本
"@scope/component1": "git+https://github.com/you/component1.git#1caf485" // 1.2.3-alpha.1
"@scope/component1": "git+https://github.com/you/component1.git#1ac2345" // 1.2.3-alpha.2
```

*** 第二种是使用 webpack 来做临时构建处理：***

```
{
  resolve: {
    modules: [
      '../', // 把父目录加到模块解析基地址中（实际写法应该是绝对地址）
      'node_modules',
    ],
    alias: {
      // 把 @scope/component1 临时定位到本地开发项目 component1 下面的构建代码，而跳过 node_modules
      '@scope/component1': 'component1/path/to/release/file',
    },
  }
}
```

**Comment by senntyou** [comment]
第二个问题我没太明白你想问什么

**Comment by winixt** [comment]
我表述的不太清楚，这其实是一个问题。

一个团队中维护了多个应用，并使多个应用之间能够优雅的共享代码（包括脚手架、代码规范、共享业务逻辑）？

* 脚手架这些基础功能虽然能够通过 cli 进行生成，但是生成之后在维护，就得在多个代码库之间同步。
* 共享基础业务逻辑（这个库改了，其他代码库也要跟着改，跟着上线的需求），这个功能确实能用你之前说的方法进行解决，但是手动成本还是比较高的。

所以我在想有没有类似 google 或者 facebook 一个代码仓库的代码管理方式，来管理前端应用。如：
http://www.ruanyifeng.com/blog/2016/07/google-monolithic-source-repository.html

目前我的想法是通过 lerna 来管理代码，把每个应用作为一个独立 package，公共的在抽离为一个 或多个package。这样整个团队的代码可以共享一套脚手架，一套代码规范。

举个例子：一个团队维护着 银行类产品和基金类产品。这两款产品作为独立的应用发布。目前有个需求：采用新的 UE 优化这两个应用的 header 部分（两个应用共用这个 header)。那么采用 npm 等形式去共享代码就需要在另一个代码库手动 update 和发布一次。而采用“一个代码库”的形式，可以做到一次更新，一次发布。

**Comment by senntyou** [comment]
估计只有大公司才有能力和精力来做这种超级大、单项目的管理吧。

另外，lerna 其实并不能完全达到你所需要的功能，lerna 还是比较适合用来做第三方库的管理，不太适合做应用管理。

组件化就是为了解耦代码、能够版本化的管理，所有的项目都放在一个 package 里面，会导致项目变得异常庞大和复杂，那就没有多少优势可言了，我感觉不太适合中小公司吧
